"""empty message

Revision ID: d5fee826c029
Revises: c419c296ffbe
Create Date: 2021-07-07 17:28:13.268446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fee826c029'
down_revision = 'c419c296ffbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description_artist', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description_artist')
    # ### end Alembic commands ###
